title: Data Analyst Portfolio
logo: Paul.jpg
description: Portfolio showcasing data analysis projects using Excel, SQL, and Power BI
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
